"""Unique username and email

Revision ID: 294a80fef7d6
Revises: 590003ebbf93
Create Date: 2014-12-04 12:52:34.083207

"""

# revision identifiers, used by Alembic.
revision = '294a80fef7d6'
down_revision = '590003ebbf93'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None)
        batch_op.drop_constraint(None)

    ### end Alembic commands ###
